/** Auto-generated by scripts/sync-web-assets.mjs — do not edit by hand */
export const webAssetManifest = [
  {
    "dir": "buttons",
    "files": [
      "pauseButton.jpg",
      "playButton.jpg"
    ]
  },
  {
    "dir": "clay",
    "files": [
      "DSCF5180.webp",
      "DSCF5182.webp",
      "DSCF5185.webp",
      "DSCF5186.webp",
      "DSCF5187.webp",
      "DSCF5188.webp",
      "DSCF5190.webp",
      "DSCF5191.webp",
      "DSCF5192.webp",
      "DSCF5194.webp",
      "IMG_7627.jpg"
    ]
  },
  {
    "dir": "logo",
    "files": [
      "logo_web.stl"
    ]
  },
  {
    "dir": "LuckyStar_candle",
    "files": [
      "background-black.jpg",
      "candle.glb",
      "DSCF5505-2.jpg",
      "ls-candle-zeitraffer.mov",
      "Luckystar_Candles_zeitraffer.mov"
    ]
  },
  {
    "dir": "mm-series",
    "files": [
      "DSCF6551.webp",
      "DSCF6553.webp",
      "DSCF6556.webp",
      "DSCF6557.webp",
      "DSCF6560.webp",
      "DSCF6622.jpg",
      "IMG_2225.jpg",
      "WhatsApp Image 2025-02-17 at 19.34.19.jpg",
      "WhatsApp Image 2025-02-17 at 19.34.22 Kopie.jpeg",
      "WhatsApp Image 2025-02-17 at 19.34.23 Kopie.jpeg"
    ]
  },
  {
    "dir": "Sound-System",
    "files": [
      "DSCF9166.jpg",
      "IMG_7178 Kopie.jpg"
    ]
  },
  {
    "dir": "step",
    "files": [
      "fräsform fusion render.pdf",
      "fräsform fusion render.png",
      "IMG_2368.jpg",
      "IMG_2369.jpg",
      "IMG_2370.jpg",
      "IMG_2371.jpg",
      "IMG_2372.jpg",
      "IMG_2373.jpg",
      "IMG_8996.jpg",
      "IMG_9055.jpg",
      "IMG_9070.jpg",
      "IMG_9075.jpg",
      "IMG_9578.jpg",
      "IMG_9586.jpg"
    ]
  }
];
