/** Auto-generated by scripts/sync-web-assets.mjs — do not edit by hand */
export const webAssetManifest = [
  {
    "dir": "buttons",
    "files": [
      "pauseButton.jpg",
      "playButton.jpg"
    ]
  },
  {
    "dir": "clay",
    "files": [
      "DSCF5180.webp",
      "DSCF5182.webp",
      "DSCF5185.webp",
      "DSCF5186.webp",
      "DSCF5187.webp",
      "DSCF5188.webp",
      "DSCF5190.webp",
      "DSCF5191.webp",
      "DSCF5192.webp",
      "DSCF5194.webp",
      "IMG_7627.jpg"
    ]
  },
  {
    "dir": "Crashbox",
    "files": [
      "Crashbox.pdf"
    ]
  },
  {
    "dir": "grillz",
    "files": [
      "3+1_textured-t.webp",
      "4-b.webp",
      "6-textured-b.webp",
      "star+1-t.webp",
      "wax-model-4-b.webp",
      "wax-on-teeth-model.webp",
      "weedleaf+4-framed.webp"
    ]
  },
  {
    "dir": "logo",
    "files": [
      "logo_web.stl"
    ]
  },
  {
    "dir": "LuckyStar_candle",
    "files": [
      "background-black.jpg",
      "candle.glb",
      "DSCF5505-2.jpg",
      "ls-candle-zeitraffer.mov",
      "Luckystar_Candles_zeitraffer.mov"
    ]
  },
  {
    "dir": "mm-series",
    "files": [
      "DSCF6551.webp",
      "DSCF6553.webp",
      "DSCF6556.webp",
      "DSCF6557.webp",
      "DSCF6560.webp",
      "DSCF6622.jpg",
      "IMG_2225.jpg",
      "WhatsApp Image 2025-02-17 at 19.34.19.jpg",
      "WhatsApp Image 2025-02-17 at 19.34.22 Kopie.jpeg",
      "WhatsApp Image 2025-02-17 at 19.34.23 Kopie.jpeg"
    ]
  },
  {
    "dir": "Sound-System",
    "files": [
      "DSCF9166.jpg",
      "IMG_7178 Kopie.jpg"
    ]
  },
  {
    "dir": "step",
    "files": [
      "fräsform fusion render.pdf",
      "fräsform fusion render.png",
      "IMG_2368.jpg",
      "IMG_2369.jpg",
      "IMG_2370.jpg",
      "IMG_2371.jpg",
      "IMG_2372.jpg",
      "IMG_2373.jpg",
      "IMG_8996.jpg",
      "IMG_9055.jpg",
      "IMG_9070.jpg",
      "IMG_9075.jpg",
      "IMG_9578.jpg",
      "IMG_9586.jpg"
    ]
  },
  {
    "dir": "threads",
    "files": [
      "coloring-threads/coloring-threads-1.JPG",
      "coloring-threads/coloring-threads-2.JPG",
      "coloring-threads/coloring-threads-3.JPG",
      "coloring-threads/threads-carpet-back.JPG",
      "coloring-threads/threads-carpet-front.JPG",
      "hanging-threads/hanging-threads-1.1.JPG",
      "hanging-threads/hanging-threads-1.JPG",
      "hanging-threads/hanging-threads-2.jpeg",
      "smiley-threads/ smiley-process.JPG",
      "smiley-threads/smiley-lamp-1.1.jpeg",
      "smiley-threads/smiley-lamp-1.JPG",
      "smiley-threads/smiley-lamp-2.jpg",
      "smiley-threads/smiley-lamp-3.JPG",
      "smiley-threads/smiley-lamp-4.jpg",
      "smiley-threads/thread-lamp-1.jpg",
      "smiley-threads/thread-lamp-2.jpeg",
      "smiley-threads/thread-lamp-process.jpg",
      "smiley-threads/thread-lamps-2.JPG",
      "smiley-threads/thread-lamps.JPG",
      "woven-threads/weaving-1.jpg",
      "woven-threads/weaving-2.jpg",
      "woven-threads/weaving-3.jpg",
      "woven-threads/weaving-4.jpg",
      "woven-threads/weaving-frame.JPG",
      "woven-threads/weaving-lamp.JPG",
      "woven-threads/woven-lamp-1.JPG",
      "woven-threads/woven-lamp.png"
    ]
  },
  {
    "dir": "x-bock",
    "files": [
      "sheet-metal-x-bock-2.webp",
      "sheet-metal-x-bock.webp",
      "x-bock-2.webp",
      "x-bock-3.webp",
      "x-bock-sit-table.webp",
      "x-bock-sit.webp",
      "x-bock-stand-desk.webp",
      "x-bock-stand.webp",
      "x-bock.webp"
    ]
  }
];
