/** Auto-generated by scripts/write-web-manifest.mjs — do not edit by hand */
export const webAssetManifest = [
  {
    "dir": "buttons",
    "files": [
      "back.webp",
      "kacheln.svg",
      "lupe.svg",
      "pauseButton.jpg",
      "playButton.jpg",
      "skip.webp"
    ]
  },
  {
    "dir": "clay",
    "files": [
      "DSCF5180.webp",
      "DSCF5182.webp",
      "DSCF5185.webp",
      "DSCF5186.webp",
      "DSCF5187.webp",
      "DSCF5188.webp",
      "DSCF5190.webp",
      "DSCF5191.webp",
      "DSCF5192.webp",
      "DSCF5194.webp",
      "IMG_7627.webp"
    ]
  },
  {
    "dir": "Crashbox",
    "files": [
      "Crashbox.pdf"
    ]
  },
  {
    "dir": "folder",
    "files": [
      "translucent-folder1.1.webp",
      "translucent-folder1.2.webp",
      "translucent-folder1.3.webp",
      "translucent-folder1.4.webp",
      "translucent-folder1.5.webp",
      "translucent-folder1.6.webp"
    ]
  },
  {
    "dir": "grillz",
    "files": [
      "3+1_textured-t.webp",
      "4-b.webp",
      "6-textured-b.webp",
      "star+1-t.webp",
      "wax-model-4-b.webp",
      "wax-on-teeth-model.webp",
      "weedleaf+4-framed.webp"
    ]
  },
  {
    "dir": "logo",
    "files": [
      "logo_web.stl"
    ]
  },
  {
    "dir": "LuckyStar_candle",
    "files": [
      "background-black.webp",
      "candle.glb",
      "DSCF5505-2.jpg",
      "ls-candle living room.webp",
      "ls-candle-zeitraffer.mp4",
      "Luckystar_Candles_zeitraffer.mp4"
    ]
  },
  {
    "dir": "mm-series",
    "files": [
      "DSCF6551.webp",
      "DSCF6553.webp",
      "DSCF6556.webp",
      "DSCF6557.webp",
      "DSCF6560.webp",
      "DSCF6622.webp",
      "IMG_2225.webp",
      "WhatsApp Image 2025-02-17 at 19.34.19.webp",
      "WhatsApp Image 2025-02-17 at 19.34.22 Kopie.webp",
      "WhatsApp Image 2025-02-17 at 19.34.23 Kopie.jpeg"
    ]
  },
  {
    "dir": "Sound-System",
    "files": [
      "DSCF9166.webp",
      "IMG_7178 Kopie.webp"
    ]
  },
  {
    "dir": "step",
    "files": [
      "fräsform fusion render.webp",
      "IMG_8996.webp",
      "IMG_9055.webp",
      "IMG_9070.webp",
      "IMG_9075.webp",
      "IMG_9578.webp",
      "IMG_9586.webp"
    ]
  },
  {
    "dir": "threads",
    "files": [
      "coloring-threads/coloring-threads-1.webp",
      "coloring-threads/coloring-threads-2.webp",
      "coloring-threads/coloring-threads-3.webp",
      "coloring-threads/threads-carpet-back.webp",
      "coloring-threads/threads-carpet-front.webp",
      "hanging-threads/hanging-threads-1.1.webp",
      "hanging-threads/hanging-threads-1.webp",
      "hanging-threads/hanging-threads-2.webp",
      "smiley-threads/ smiley-process.webp",
      "smiley-threads/smiley-lamp-1.1.webp",
      "smiley-threads/smiley-lamp-1.webp",
      "smiley-threads/smiley-lamp-2.webp",
      "smiley-threads/smiley-lamp-3.webp",
      "smiley-threads/smiley-lamp-4.webp",
      "smiley-threads/thread-lamp-1.webp",
      "smiley-threads/thread-lamp-2.webp",
      "smiley-threads/thread-lamp-process.webp",
      "smiley-threads/thread-lamps-2.webp",
      "smiley-threads/thread-lamps.webp",
      "woven-threads/weaving-1.jpg",
      "woven-threads/weaving-2.jpg",
      "woven-threads/weaving-3.jpg",
      "woven-threads/weaving-4.jpg",
      "woven-threads/weaving-frame.webp",
      "woven-threads/weaving-lamp.webp",
      "woven-threads/woven-lamp-1.webp",
      "woven-threads/woven-lamp.webp"
    ]
  },
  {
    "dir": "worldd2023",
    "files": [
      "worldd.video(sped up).mp4"
    ]
  },
  {
    "dir": "x-bock",
    "files": [
      "sheet-metal-x-bock-2.webp",
      "sheet-metal-x-bock.webp",
      "x-bock-2.webp",
      "x-bock-3.webp",
      "x-bock-sit-table.webp",
      "x-bock-sit.webp",
      "x-bock-stand-desk.webp",
      "x-bock-stand.webp",
      "x-bock.webp"
    ]
  }
];
