import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.join(__dirname, "..", "..");

/** Alle Dateien unter einem Asset-Topordner, relativ mit `/` (Unterordner bleiben erhalten). */
export function collectFilesRecursive(dirPath, relBase = "") {
  const out = [];
  for (const ent of fs.readdirSync(dirPath, { withFileTypes: true })) {
    if (ent.name.startsWith(".")) continue;
    const rel = relBase ? `${relBase}/${ent.name}` : ent.name;
    const full = path.join(dirPath, ent.name);
    if (ent.isDirectory()) {
      out.push(...collectFilesRecursive(full, rel));
    } else if (ent.isFile()) {
      out.push(rel);
    }
  }
  return out.sort((a, b) => a.localeCompare(b));
}

export function buildManifest(webRoot) {
  const rows = [];
  for (const name of fs.readdirSync(webRoot, { withFileTypes: true })) {
    if (name.name.startsWith(".") || !name.isDirectory()) continue;
    const dirPath = path.join(webRoot, name.name);
    const files = collectFilesRecursive(dirPath);
    rows.push({ dir: name.name, files });
  }
  rows.sort((a, b) => a.dir.localeCompare(b.dir));
  return rows;
}

/**
 * @param {ReturnType<typeof buildManifest>} rows
 * @param {{ generatedBy?: string }} [opts]
 */
export function writeManifest(rows, opts = {}) {
  const generatedBy = opts.generatedBy ?? "scripts/sync-web-assets.mjs";
  const body = `/** Auto-generated by ${generatedBy} — do not edit by hand */
export const webAssetManifest = ${JSON.stringify(rows, null, 2)};
`;
  fs.writeFileSync(path.join(ROOT, "lib", "webAssetManifest.js"), body, "utf8");
}
